<script>
    window.LifNetworkConfig = {
        treeUrl: '{{ $treeUrl ?? route("network.tree") }}',
        statsUrl: '{{ $statsUrl ?? route("network.stats") }}',
        plansUrl: '{{ $plansUrl ?? route("network.plans") }}',
        searchUrl: '{{ $searchUrl ?? route("network.search") }}',
        panelUrl: '{{ $panelUrl ?? route("network.panel") }}',
        childrenUrl: '{{ $childrenUrl ?? route("network.children") }}',
        clickBehavior: '{{ $clickBehavior ?? "panel" }}',
        isAdmin: {{ isset($config) && $config['is_admin'] ? 'true' : 'false' }},
        adminProfileUrl: '{{ url("/customer/profile/details") }}',
        baseUserId: {{ isset($baseUserId) ? (int) $baseUserId : (auth()->id() ?? 'null') }},
        maxDepthLimit: {{ $maxDepthLimit ?? 5 }},
    };

    window.LifNetworkLabels = {
        children: @json(__('tree.nodes_children')),
        directs: @json(__('tree.directs_label')),
        points: @json(__('tree.points_label')),
        loading: @json(__('tree.loading')),
        others: @json(__('tree.others')),
        viewDetails: @json(__('tree.view_details')),
        networkPoints: @json(__('tree.network_points')),
        personalPoints: @json(__('tree.personal_points')),
        allGenerations: @json(__('tree.all_generations')),
        allLevels: @json(__('tree.all_levels')),
        generationOnly: @json(__('tree.level_only', ['level' => ':level'])),
        upToGeneration: @json(__('tree.level_up_to', ['level' => ':level'])),
        memberSince: @json(__('tree.member_since', ['year' => ':year'])),
        activeStatus: @json(__('tree.active_status')),
        viewProfile: @json(__('tree.view_profile')),
        panelPlan: @json(__('tree.panel_plan')),
        panelDiscount: @json(__('tree.panel_discount')),
        noPlan: @json(__('tree.no_plan')),
        generations: @json(__('tree.generations')),
        searchNotFound: @json(__('tree.search_not_found')),
        searchNotAllowed: @json(__('tree.search_not_allowed')),
        searchEmpty: @json(__('tree.search_empty')),
        searchError: @json(__('tree.search_error')),
        backToRoot: @json(__('tree.back_to_root')),
        nextPlanLabel: @json(__('tree.next_plan')),
        progressLabel: @json(__('tree.progress_label')),
        targetPointsLabel: @json(__('tree.target_points_label')),
        maxPlanLabel: @json(__('tree.max_plan_label')),
        allPlans: @json(__('tree.all_plans')),
        upToLevelPrefix: @json(__('tree.up_to_level', ['level' => ''])),
    };
</script>
<script src="{{ asset('/public/js/network-tree.js') }}"></script>
