<?php

use Illuminate\Support\Facades\DB;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class AddDoubleApprovalOnNotificationSettingsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        // Insertamos la configuración para la nueva notificación
        DB::table('notification_settings')->insert([
            'event' => json_encode(['en' => 'Double Approval Request']),
            'slug' => 'double-approval-request',
            'type' => 'system,email', // Activadas por defecto según el estándar
            'message' => json_encode([
                'en' => 'The user [sender_name] has requested your approval for a parametric change.'
            ]),
            'admin_msg' => json_encode([
                'en' => 'A new double approval request has been generated by [sender_name].'
            ]),
            'user_access_status' => 1,
            'seller_access_status' => 0,
            'admin_access_status' => 1,
            'staff_access_status' => 1,
            'module' => 'GeneralSetting',
            'created_at' => now(),
            'updated_at' => now(),
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        DB::table('notification_settings')->where('slug', 'double-approval-request')->delete();
    }
}
